### PR TITLE
Update Python Fundamentals_Guided Project.ipynb

### PR DESCRIPTION
**Pull request by am-stead**

### CODE REVIEW

**Comment by Walizkasz** [comment]
Yhx

**Comment by sarfaraz3232** [comment]
### love you so much 😘

Uploading 2025-01-09-081017704.mp4…

**Comment by sarfaraz3232** [comment]
Looking for ❤️

**Comment by sarfaraz3232** [comment]
****

**Comment by sarfaraz3232** [comment]
♥️♥️♥️♥️

**Comment by sarfaraz3232** [comment]
Like dis like.love this video 🔥🦅💪🏻

**Comment by sarfaraz3232** [comment]
[Check unallowed file changes](https://github.com/github/docs/actions/workflows/triage-unallowed-contributions.yml)

**Comment by sky1-dot** [comment]
Hi

**Pull request merged**
